// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CoffeeLibrary$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CoffeeLibrary";
  readonly sourceName: "contracts/Library.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220d7d3f19f0597770e751278180eb6ac446fa6caf0a370ce575946357820ea8f4864736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220d7d3f19f0597770e751278180eb6ac446fa6caf0a370ce575946357820ea8f4864736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Library.sol";
  readonly buildInfoId: "solc-0_8_20-9ea3872be80c6fa020554fa93980fac622220487";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CoffeeLibrary"]: CoffeeLibrary$Type;
    ["contracts/Library.sol:CoffeeLibrary"]: CoffeeLibrary$Type;
  }
}